### ISSUE TITLE
cant change registers 

### ISSUE THREAD

**Issue by TheYigidOS** [cybcon/modbus-server#18]
when i run this code all registers are 0  with this json file 

from pyModbusTCP.client import ModbusClient

server_ip = "0.0.0.0"  
server_port = 5020  

client = ModbusClient(server_ip, server_port)

if client.open():
    
    
    start_register = 1
    num_registers = 10

    
    data = client.read_holding_registers(start_register, num_registers)

    if data:
        print("Okunan veriler:", data)
    else:
        print("Veri okuma başarısız.")

    
    client.close()
else:
    print("Sunucuya bağlanılamadı.")

{
  "server": {
    "listenerAddress": "0.0.0.0",
    "listenerPort": 5020,
    "tlsParams": {
      "description": "path to certificate and private key to enable tls",
      "privateKey": null,
      "certificate": null
      },
    "logging": {
      "format": "%(asctime)-15s %(threadName)-15s  %(levelname)-8s %(module)-15s:%(lineno)-8s %(message)s",
      "logLevel": "DEBUG"
      }
    },
  "registers": {
    "description": "initial values for the register types",
    "zeroMode": true,
    "initializeUndefinedRegisters": true,
    "discreteInput": {},
    "coils": {},
  "holdingRegister": {
      "0": "0x0000",
      "1": "0x0001",
      "2": "0x0002",
      "3": "0x0003",
      "4": "0x0004",
      "5": "0x0005",
      "6": "0x0006",
      "7": "0x0007",
      "8": "0x0008",
      "9": "0x0009",
      "10": "0x000A",
      "11": "0x000B",
      "12": "0x000C",
      "13": "0x000D",
      "14": "0x000E",
      "15": "0x000F",
      "16": "0x0010",
      "17": "0x0011",
      "18": "0x0012",
      "19": "0x0013",
      "20": "0x0014",
      "21": "0x0015",
      "22": "0x0016",
      "23": "0x0017",
      "24": "0x0018",
      "25": "0x0019",
      "26": "0x001A",
      "27": "0x001B",
      "28": "0x001C",
      "29": "0x001D",
      "30": "0x001E",
      "31": "0x001F",
      "32": "0x0020",
      "33": "0x0021",
      "34": "0x0022",
      "35": "0x0023",
      "36": "0x0024",
      "37": "0x0025",
      "38": "0x0026",
      "39": "0x0027",
      "40": "0x0028",
      "41": "0x0029",
      "42": "0x002A",
      "43": "0x002B",
      "44": "0x002C",
      "45": "0x002D",
      "46": "0x002E",
      "47": "0x002F",
      "48": "0x0030",
      "49": "0x0031",
      "50": "0x0032",
      "51": "0x0033",
      "52": "0x0034",
      "53": "0x0035",
      "54": "0x0036",
      "55": "0x0037",
      "56": "0x0038",
      "57": "0x0039",
      "58": "0x003A",
      "59": "0x003B",
      "60": "0x003C",
      "61": "0x003D",
      "62": "0x003E",
      "63": "0x003F",
      "64": "0x0040",
      "65": "0x0041",
      "66": "0x0042",
      "67": "0x0043",
      "68": "0x0044",
      "69": "0x0045",
      "70": "0x0046",
      "71": "0x0047",
      "72": "0x0048",
      "73": "0x0049",
      "74": "0x004A",
      "75": "0x004B",
      "76": "0x004C",
      "77": "0x004D",
      "78": "0x004E",
      "79": "0x004F",
      "80": "0x0050",
      "81": "0x0051",
      "82": "0x0052",
      "83": "0x0053",
      "84": "0x0054",
      "85": "0x0055",
      "86": "0x0056",
      "87": "0x0057",
      "88": "0x0058",
      "89": "0x0059",
      "90": "0x005A",
      "91": "0x005B",
      "92": "0x005C",
      "93": "0x005D",
      "94": "0x005E",
      "95": "0x005F",
      "96": "0x0060",
      "97": "0x0061",
      "98": "0x0062",
      "99": "0x0063"
      },
    "inputRegister": {
      "0": "0x84D9",
      "1": "0x41ED",
      "3": "0xC24C",
      "5": "0xBF80",
      "6": "0x0068",
      "7": "0x006C",
      "8": "0x0074",
      "9": "0x0032",
      "426": "0x0039",
      "427": "0x0038",
      "428": "0x0038",
      "429": "0x001B",
      "430": "0x001A",
      "431": "0x001A",
      "456": "0x3F80",
      "457": "0x6666",
      "458": "0x4086",
      "459": "0x0002",
      "460": "0x0001",
      "461": "0x0002",
      "466": "0x0032",
      "467": "0x0001",
      "475": "0x0066",
      "476": "0x0002",
      "477": "0x0001",
      "478": "0x0002",
      "483": "0x0032",
      "484": "0x0001",
      "492": "0x0066",
      "493": "0x0002",
      "494": "0x0001",
      "495": "0x0002",
      "500": "0x0032",
      "501": "0x0001",
      "509": "0x0066",
      "510": "0x0002",
      "511": "0x0001",
      "512": "0x0002",
      "517": "0x0032",
      "518": "0x0001",
      "526": "0x0066",
      "527": "0x0002",
      "528": "0x0001",
      "529": "0x0002",
      "534": "0x0032",
      "535": "0x0001",
      "543": "0x0066",
      "544": "0x0002",
      "545": "0x0001",
      "546": "0x0002",
      "551": "0x0032",
      "552": "0x0001",
      "560": "0x0066"
      }
    }
  }

**Comment by Bagunda** [comment]
Same problem

**Comment by Bagunda** [comment]
Same problem
![ezgif com-gif-maker](https://github.com/cybcon/modbus-server/assets/16766521/8f8ece4d-2a3f-471c-854f-bd10f04f83cb)

**Comment by cybcon** [comment]
Hi @all - thank you for inform me about an issue.
I tried to reproduce the issue with the oitc/modbus-server:1.1.3 docker container.

A created a json file with following input:
```json
{
"server": {
  "listenerAddress": "0.0.0.0",
  "listenerPort": 5020,
  "tlsParams": {
    "description": "path to certificate and private key to enable tls",
    "privateKey": null,
    "certificate": null
    },
  "logging": {
    "format": "%(asctime)-15s %(threadName)-15s  %(levelname)-8s %(module)-15s:%(lineno)-8s %(message)s",
    "logLevel": "DEBUG"
    }
  },
"registers": {
  "description": "initial values for the register types",
  "zeroMode": false,
  "initializeUndefinedRegisters": true,
  "discreteInput": {
    "1": "0xAA01",
    "2": "0xAA02",
    "3": "0xAA03",
    "4": "0xAA04"
  },
  "coils": {
    "1": "0xBB01",
    "2": "0xBB02",
    "3": "0xBB03",
    "4": "0xBB04"
  },
  "holdingRegister": {
    "1": "0xCC01",
    "2": "0xCC02",
    "3": "0xCC03",
    "4": "0xCC04"
    },
  "inputRegister": {
    "1": "0xDD01",
    "2": "0xDD02",
    "3": "0xDD03",
    "4": "0xDD04"
    }
  }
}
```
and started my docker container with:
```
docker run --rm -p 5020:5020 -v /srv/docker/server_config.json:/server_config.json oitc/modbus-server:latest -f /server_config.json
```

After that I used the `oitc/modbus-client:latest` command line tool to read the analog output holding registers (Register ID 3):
```
docker run --rm oitc/modbus-client:latest -s 192.168.57.10 -p 5020 -t 3 -r 0 -l 5
           HEX16  UINT16  INT16               BIT       HEX32          FLOAT32
register
40000     0xCC01   52225 -13311  1100110000000001  0xCC010000 -33816576.000000
40001     0xCC02   52226 -13310  1100110000000010  0xCC02CC01 -34287620.000000
40002     0xCC03   52227 -13309  1100110000000011  0xCC03CC02 -34549768.000000
40003     0xCC04   52228 -13308  1100110000000100  0xCC04CC03 -34811916.000000
40004     0x0000       0      0  0000000000000000  0x0000CC04         0.000000
```
The server shows following log:
```
2023-11-05 10:08:17,477 MainThread       DEBUG    sync           :348      Started thread to serve client at ('10.243.0.1', 39070)
2023-11-05 10:08:17,480 Thread-5 (process_request_thread)  DEBUG    sync           :46       Client Connected [10.243.0.1:39070]
2023-11-05 10:08:17,481 Thread-5 (process_request_thread)  DEBUG    sync           :199      Handling data: 0x0 0x1 0x0 0x0 0x0 0x6 0x1 0x3 0x0 0x0 0x0 0x5
2023-11-05 10:08:17,485 Thread-5 (process_request_thread)  DEBUG    socket_framer  :147      Processing: 0x0 0x1 0x0 0x0 0x0 0x6 0x1 0x3 0x0 0x0 0x0 0x5
2023-11-05 10:08:17,486 Thread-5 (process_request_thread)  DEBUG    factory        :137      Factory Request[ReadHoldingRegistersRequest: 3]
2023-11-05 10:08:17,486 Thread-5 (process_request_thread)  DEBUG    context        :63       validate: fc-[3] address-1: count-5
2023-11-05 10:08:17,512 Thread-5 (process_request_thread)  DEBUG    context        :77       getValues fc-[3] address-1: count-5
2023-11-05 10:08:17,513 Thread-5 (process_request_thread)  DEBUG    sync           :229      send: [ReadHoldingRegistersResponse (5)]- b'00010000000d01030acc01cc02cc03cc040000'
2023-11-05 10:08:17,518 Thread-5 (process_request_thread)  DEBUG    sync           :199      Handling data:
2023-11-05 10:08:17,518 Thread-5 (process_request_thread)  DEBUG    socket_framer  :147      Processing:
2023-11-05 10:08:17,518 Thread-5 (process_request_thread)  DEBUG    sync           :54       Client Disconnected [10.243.0.1:39070]
```

and read the analog input registers (Register ID 4):
```
docker run --rm oitc/modbus-client:latest -s 192.168.57.10 -p 5020 -t 4 -r 0 -l 5
           HEX16  UINT16  INT16               BIT       HEX32  \
register
30000     0xDD01   56577  -8959  1101110100000001  0xDD010000
30001     0xDD02   56578  -8958  1101110100000010  0xDD02DD01
30002     0xDD03   56579  -8957  1101110100000011  0xDD03DD02
30003     0xDD04   56580  -8956  1101110100000100  0xDD04DD03
30004     0x0000       0      0  0000000000000000  0x0000DD04
[..]
```
the server shows following log:
```
2023-11-05 10:10:49,412 MainThread       DEBUG    sync           :348      Started thread to serve client at ('10.243.0.1', 38430)
2023-11-05 10:10:49,414 Thread-6 (process_request_thread)  DEBUG    sync           :46       Client Connected [10.243.0.1:38430]
2023-11-05 10:10:49,414 Thread-6 (process_request_thread)  DEBUG    sync           :199      Handling data: 0x0 0x1 0x0 0x0 0x0 0x6 0x1 0x4 0x0 0x0 0x0 0x5
2023-11-05 10:10:49,414 Thread-6 (process_request_thread)  DEBUG    socket_framer  :147      Processing: 0x0 0x1 0x0 0x0 0x0 0x6 0x1 0x4 0x0 0x0 0x0 0x5
2023-11-05 10:10:49,415 Thread-6 (process_request_thread)  DEBUG    factory        :137      Factory Request[ReadInputRegistersRequest: 4]
2023-11-05 10:10:49,415 Thread-6 (process_request_thread)  DEBUG    context        :63       validate: fc-[4] address-1: count-5
2023-11-05 10:10:49,426 Thread-6 (process_request_thread)  DEBUG    context        :77       getValues fc-[4] address-1: count-5
2023-11-05 10:10:49,436 Thread-6 (process_request_thread)  DEBUG    sync           :229      send: [ReadInputRegistersResponse (5)]- b'00010000000d01040add01dd02dd03dd040000'
2023-11-05 10:10:49,444 Thread-6 (process_request_thread)  DEBUG    sync           :199      Handling data:
2023-11-05 10:10:49,446 Thread-6 (process_request_thread)  DEBUG    socket_framer  :147      Processing:
2023-11-05 10:10:49,447 Thread-6 (process_request_thread)  DEBUG    sync           :54       Client Disconnected [10.243.0.1:38430]
```


And get the values as configured in the JSON configuration file.

For the Discrete Output Coils (ID 1) and Discrete Input Contacts (ID 2) I faced and bug in the modbus-client tool. I will create an issue here but for holding and input registers it works well on my side.

@TheYigidOS Do you use the python code for modbus-server on your machine directly or do you use the docker container `oitc/modbus-server`?
If you use the python code directly, please note that you need to use `pymodbus >= 2, < 3`
But I will check your code now more in detail to reproduce your issue.

@Bagunda You try to write registers in your test, but this was never tested with the server and also currently not supported. The server is just a simple Modbus server for read requests of static values. I initially wrote the server for enhanced Modbus TCP mocking for an IoT gateway functionality test.
But your read seams to be correct - the server showed the correct vaues in the log that will be send back to your client:
![grafik](https://github.com/cybcon/modbus-server/assets/42999275/7aea8f5a-2d95-4d2b-b7dc-e9e9286a77f9)

**Comment by cybcon** [comment]
@TheYigidOS 
I installed the python module `pyModbusTCP` in version 0.2.0 
I used your python code and set the valid IP address of my modbus server:

```python
from pyModbusTCP.client import ModbusClient

server_ip = "192.168.57.10"
server_port = 5020

client = ModbusClient(server_ip, server_port)

if client.open():
  start_register = 1
  num_registers = 10

  data = client.read_holding_registers(start_register, num_registers)

  if data:
    print("Okunan veriler:", data)
  else:
    print("Veri okuma başarısız.")

  client.close()

else:
  print("Sunucuya bağlanılamadı.")
```

I used the given json file in your comment and startet the server with:
```
docker run --rm -p 5020:5020 -v /srv/docker/server_config.json:/server_config.json oitc/modbus-server:latest -f /server_config.json
```

If I now start the python code - I get following response:
```
# python test.py
Okunan veriler: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
```

this is exactly what is configured in your json:
```
"1": "0x0001",
"2": "0x0002",
"3": "0x0003",
"4": "0x0004",
"5": "0x0005",
"6": "0x0006",
"7": "0x0007",
"8": "0x0008",
"9": "0x0009",
"10": "0x000A",
```

**Comment by Bagunda** [comment]
> @BagundaВы пытаетесь записать регистры в своем тесте, но это никогда не тестировалось на сервере и в настоящее время не поддерживается. Сервер представляет собой простой сервер Modbus для запросов на чтение статических значений. Первоначально я написал сервер для расширенного моделирования Modbus TCP для проверки функциональности шлюза IoT.
> Но ваше чтение кажется правильным - сервер показал правильные значения в журнале, которые будут отправлены обратно вашему клиенту:
> ![графика](https://user-images.githubusercontent.com/42999275/280520210-7aea8f5a-2d95-4d2b-b7dc-e9e9286a77f9.png)



> @BagundaВы пытаетесь записать регистры в своем тесте, но это никогда не тестировалось на сервере и в настоящее время не поддерживается. Сервер представляет собой простой сервер Modbus для запросов на чтение статических значений. Первоначально я написал сервер для расширенного моделирования Modbus TCP для проверки функциональности шлюза IoT.
> Но ваше чтение кажется правильным - сервер показал правильные значения в журнале, которые будут отправлены обратно вашему клиенту:
> ![графика](https://user-images.githubusercontent.com/42999275/280520210-7aea8f5a-2d95-4d2b-b7dc-e9e9286a77f9.png)

У меня оказалось, что не работает крякнутый Modbus Poll.
Переустановил и он начал отображать всё нормально.
И запись всегда проходила нормально без каких либо проблем.
Спасибо вам за такую шикарную работу!
Ничего боле-менее вменяемого я так и не нашёл.
Только ваша программа работает нормально.
Но нет документации как убрать море логов, которые за несколько дней съедают у меня 10Гб HDD.
И чтобы очистить логи приходилось делать вот так:
```
: > /var/log/user.log
: > /var/log/syslog
```
Эти команды очищали данные файлы в ноль.
Будучи немного программистом, я догадался, что надо изменить строку `"logLevel": "DEBUG"`, но на что менять не написано. Изменил на `"INFO"` и логи перестали забивать мне всю память.

Я плохо разбираюсь в докере.
У меня никак не получается сделать, чтобы программа работала после перезагрузки.

Я использую вашу программу на одном большом объекте, на котором работаю над промышленной вентиляцией.
Мы планировали, что Modbus TCP Server (Slave) будет жить на iRidium Server offline version.
Но эта функция там работает очень плохо.
А работы производить надо.
Поэтому на несколько месяцев ваша программа будет трудиться в боевом режиме, пока я не придумаю чем заменить.

**Comment by Bagunda** [comment]
Ещё не хватает функции, чтобы после ребута сохранялись данные до ребута.
Это конечно может убить накопитель, но хотелось бы иметь такую функцию

**Comment by cybcon** [comment]
@Bagunda Thank you for your response.
It's a good point. I need to enhance the Documentation of the json config file.
I will do this asap.

Regarding logging you may have a look at the docker logging config options.
https://docs.docker.com/config/containers/logging/configure/

You can limit the max logsize here.

**Comment by cybcon** [comment]
@Bagunda I enhanced the README.md in PR #22

**Comment by TheYigidOS** [comment]
Guys thank you for all my supporters, but i just forgat add 1 line to compose file

**Comment by TheYigidOS** [comment]
can i set dec values instead of hex
"1": "0x0001",
"2": "255", (or)
"3": 255,
