### ISSUE TITLE
Docker disk is growing very fast

### ISSUE THREAD

**Issue by michelferia** [cybcon/modbus-server#23]
Hello,

I'm running the modbus-server and I see the docker disk image growing without control, maybe is the log?
how to find the logs files and how to stop logging ?
thanks in advance!
kind regards,

**Comment by cybcon** [comment]
Hi @michelferia 
The log severity can be changed from DEBUG to INFO (or WARN, or ERROR) this will limit the log output of the modbus-server.
The modbus-server wil log to stdout. That means the logging configuration of your docker subsystem seams to be missconfigured.

In `/etc/docker/daemon.json` of your docker hostsystem you can configure the logging facility.
e.g. you can configure log options such as a maximum logsize:
```
[..]
  "log-opts": {
    "max-size": "10m",
    "max-file": "10"
  },
[..]
```

Regarding logging you may have a look at the docker logging config options.
https://docs.docker.com/config/containers/logging/configure/

**Comment by michelferia** [comment]
Hi,
Thanks very much for the prompt reply, it's much appreciated!
Thanks very much for your image, it's really nice ;-)

kind regards,
MF

**Comment by cybcon** [comment]
PR #24
changes log severity inside the container from DEBUG to INFO - hope that helps
