### ISSUE TITLE
Issues with "latest" docker build.

### ISSUE THREAD

**Issue by rwskinner** [cybcon/modbus-server#38]
7.738 ERROR: unable to select packages:
7.739   python3-3.11.9-r0:
7.739     breaks: world[python3=3.11.8-r0]
7.739     satisfies: python3-3.11.9-r0[python3~3.11]
7.739                py3-parsing-pyc-3.1.1-r0[python3]
7.739                py3-parsing-pyc-3.1.1-r0[python3~3.11]
7.739                py3-pip-23.3.1-r0[python3]
7.739                py3-pip-23.3.1-r0[python3~3.11]
7.739                py3-setuptools-68.2.2-r0[python3]
7.739                py3-setuptools-68.2.2-r0[python3~3.11]
7.739                py3-parsing-3.1.1-r0[python3]
7.739                py3-parsing-3.1.1-r0[python3~3.11]
7.739                py3-packaging-23.2-r0[python3]
7.739                py3-packaging-23.2-r0[python3~3.11]
7.739                py3-packaging-pyc-23.2-r0[python3]
7.739                py3-packaging-pyc-23.2-r0[python3~3.11]
------
Dockerfile:6
--------------------
   5 |
   6 | >>> RUN apk upgrade --available --no-cache --update \
   7 | >>>     && apk add --no-cache --update \
   8 | >>>        python3=3.11.8-r0 \
   9 | >>>        py3-pip=23.3.1-r0 \
  10 | >>>     # Cleanup APK
  11 | >>>     && rm -rf /var/cache/apk/* /tmp/* /var/tmp/*
  12 |
--------------------
ERROR: failed to solve: process "/bin/sh -c apk upgrade --available --no-cache --update     && apk add --no-cache --update        python3=3.11.8-r0        py3-pip=23.3.1-r0     && rm -rf /var/cache/apk/* /tmp/* /var/tmp/*" did not complete successfully: exit code: 7

**Comment by rwskinner** [comment]
Using Alpine 3.20.1 then removing versions for python3 and pip worked.

**Comment by cybcon** [comment]
Hi @rwskinner,

I use the best practice of version pinning inside the Dockerfile. It's a finding in Hadolint.
So the error is a know issue and also in some cases wanted behaviour to make transparent that things had changed and needs to be validated manually.
The ready to use container is available on dockerhub.
But anyhow, I will upgrade the container dependencies and give you a hint here in the chat.

Best regards

**Comment by cybcon** [comment]
Upgrade references #39
